---
title: Een blok maken
hero_image: afbeeldingen/banner.png
description: Een blok maken
theme: rood
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: builder, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: ""
technologies: "scratch"
site_areas:
steps:
  - 
    title: Een blok maken
