title: generic-scratch3-make-block
hero_image: images/banner.png
description: generic-scratch3-make-block description
version: 4
listed: false
copyedit: false
last_tested: "2018-11-05"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
